name: AWS Ansible Testing

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
        architecture: x64
    - name: List Actions
      run: ls -l /home/runner/work/_actions/actions/
    - uses: actions/aws@master
    - name: Run
      run: python --version